
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'kien/ctrlp.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'w0rp/ale'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'seeamkhan/robotframework-vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
Plugin 'hashivim/vim-terraform'

" All of your Plugins must be added before the following line
call vundle#end()            " required

" hi ColorColumn guibg=gray ctermbg=gray
highlight RedundantSpaces term=standout ctermbg=red guibg=red
match RedundantSpaces /\s\+$\| \+\ze\t/

filetype plugin indent on    " required
set wrap
map <C-n> :NERDTreeToggle<CR>
set runtimepath^=~/.vim/bundle/ctrlp.vim
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,.git/*,WEB-INF/*,**/img/*,.git*,*.egg,*_components/**,*node_modules/**,build/**,env/**

let g:ctrlp_custom_ignore = '\v[\/](WEB-INF|env)$'
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'

" CtrlP mappings

nmap <leader>lw :CtrlP<CR><C-\>w

cmap :tabl tabe<CR>:tabo<CR>

" Font

if has('gui_running')
    set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h11
endif

" Clearly this only works with airline enabled with powerline fonts
let g:airline_powerline_fonts = 1



"  detect indent!
" autocmd BufReadPost * :DetectIndent
" autocmd BufWritePost *.py call Flake8()
" let g:detectindent_preferred_expandtab = 1
" let g:syntastic_python_checkers = ['flake8', 'pylint']

au BufNewFile,BufRead *.robot setlocal filetype=robot

set wildmode=list:longest
set wildignore=*.pyc
set ts=4
set sw=4
set ls=2
set ai
set si
set incsearch
set expandtab
set number
set nowrap
set ruler
syntax on
set colorcolumn=80
" execute "set colorcolumn=" . join(range(81,335), ',')
set guioptions=egmt
set so=5
set lcs=tab:>-,trail:-
" maak hier ff GUI only regels van
" highlight guifg=gray
syntax on
filetype plugin indent on

" colors and styling
set t_Co=256
colorscheme gruvbox
set bg=dark
set gfn=DejaVu\ Sans\ Mono\ for\ Powerline:h13
" weird thing with MacOS
set backspace=2

set wrap
